ip: "127.0.0.1"
port: 8082
api:
  max_message_size: 32
usecase:
  default_message_query: "Hello, stranger!" 
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: ""
  dbname: "sandbox"
